services:
  profile-api-service:
    container_name: profile-api-service
    build:
      context: .
      dockerfile: PLServices/ProfileApiService/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PROFILE_BACKEND_URL: http://profile-backend-service:5001
      HTTP_PORT: 8080
      GRPC_PORT: 8081
    depends_on:
      - profile-backend-service  
    networks:
      - app-network
      
  profile-backend-service:
    container_name: profile-backend-service  
    build:
      context: .
      dockerfile: BLServices/ProfileBackendService/Dockerfile
    restart: unless-stopped
    environment:
      PROFILE_DATABASE_URL: http://profile-database-service:6001
      HTTP_PORT: 5000
      GRPC_PORT: 5001
    depends_on:
      - profile-database-service
    networks:
      - app-network

  profile-database-service:
    container_name: profile-database-service
    build:
      context: .
      dockerfile: DALServices/ProfileDatabaseService/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - profile_db
      - profile_db_migrator
    networks:
      - app-network
      
  profile_db:
    image: postgres:15
    container_name: profile_db
    restart: always   
    ports:
      - "5434:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ProfileServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    networks:
      - app-network

  profile_db_migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: profile_db_migrator
    restart: on-failure
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        dotnet tool install --global dotnet-ef &&
        export PATH="/usr/local/bin:/usr/bin:/bin:/root/.dotnet/tools" &&
        dotnet ef database update --project DALServices/ProfileDatabaseService/ProfileDatabaseService.csproj \
                                  --startup-project DALServices/ProfileDatabaseService/ProfileDatabaseService.csproj
    depends_on:
      - profile_db     
    networks:
      - app-network      

networks:
  app-network:
    driver: bridge
 
volumes:
  database-data:
