services:
#Профиль
  profile-api-service:
    container_name: profile-api-service
    build:
      context: .
      dockerfile: PLServices/ProfileApiService/Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      PROFILE_BACKEND_URL: http://profile-backend-service:5001
      HTTP_PORT: 8080
      GRPC_PORT: 8081
    depends_on:
      - profile-backend-service  
    networks:
      - app-network
      
  profile-backend-service:
    container_name: profile-backend-service  
    build:
      context: .
      dockerfile: BLServices/ProfileBackendService/Dockerfile
    restart: unless-stopped
    environment:
      PROFILE_DATABASE_URL: http://profile-database-service:6001
      HTTP_PORT: 5000
      GRPC_PORT: 5001
    depends_on:
      - profile-database-service
    networks:
      - app-network

  profile-database-service:
    container_name: profile-database-service
    build:
      context: .
      dockerfile: DALServices/ProfileDatabaseService/Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - profile_db
      - profile_db_migrator
    networks:
      - app-network
      
  profile_db:
    image: postgres:15
    container_name: profile_db
    restart: always   
    ports:
      - "5434:5432"
    volumes:
      - profile-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ProfileServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    networks:
      - app-network

  profile_db_migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: profile_db_migrator
    restart: on-failure
    env_file:
      - .env
    working_dir: /app
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        dotnet tool install --global dotnet-ef &&
        export PATH="/usr/local/bin:/usr/bin:/bin:/root/.dotnet/tools" &&
        dotnet ef database update --project DALServices/ProfileDatabaseService/ProfileDatabaseService.csproj \
                                  --startup-project DALServices/ProfileDatabaseService/ProfileDatabaseService.csproj
    depends_on:
      - profile_db     
    networks:
      - app-network
      
# Email
  email-service:
    container_name: email-service
    build:
      context: .
      dockerfile: Services/EmailService/Dockerfile
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_HOST: email_db
      DB_PORT: 5432
      POSTGRES_DB: EmailServiceDb
      DB_USER: postgres
      DB_PASSWORD: 123456789
      RabbitMQ: rabbitmq
    depends_on:
      - email_db
      - email_db_migrator
    networks:
      - app-network
      
  email_db:
    image: postgres:15
    container_name: email_db
    restart: always   
    ports:
      - "5435:5432"
    volumes:
      - email-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: EmailServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    networks:
      - app-network

  email_db_migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: email_db_migrator
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_HOST: email_db
      DB_PORT: 5432
      POSTGRES_DB: EmailServiceDb
      DB_USER: postgres
      DB_PASSWORD: 123456789
    working_dir: /app
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        dotnet tool install --global dotnet-ef &&
        export PATH="/usr/local/bin:/usr/bin:/bin:/root/.dotnet/tools" &&
        dotnet ef database update --project Services/EmailService/EmailService.csproj \
                                  --startup-project Services/EmailService/EmailService.csproj
    depends_on:
      - email_db     
    networks:
      - app-network

# UI      
  old-strategy-forge-ui-service:
    container_name: old-strategy-forge-ui-service
    build:
      context: .
      dockerfile: FrontendService/Dockerfile
    restart: unless-stopped
    ports:
      - "80801:80801"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RabbitMQ: rabbitmq
    networks:
      - app-network

# Утилиты
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=mixaila17may2003@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Test1234
    ports:
      - "5050:80"
    networks:
      - app-network
   
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network
          
networks:
  app-network:
    driver: bridge
 
volumes:
  profile-database-data:
  email-database-data:
