services:
  frontend-service:
    build:
      context: ./FrontendService
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    networks:
      - app-network

  backend-service:
    build:
      context: ./BackendService
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    networks:
      - app-network

  database-service:
    build:
      context: ./DatabaseService
      dockerfile: Dockerfile
    ports:
      - "5002:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
