services:
# API Gateway
  api-gateway:
    container_name: api-gateway
    image: ghcr.io/panixida/api-gateway:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: production
    networks:
      - app-network

# GamePlay
  game-play-service:
    container_name: game-play-service
    image: ghcr.io/panixida/game-play-service:latest
    restart: unless-stopped
    ports:
      - "7777:7777/udp"
    environment:
      ASPNETCORE_ENVIRONMENT: production
    networks:
      - app-network

# Profile     
  profile-service:
    container_name: profile-service
    image: ghcr.io/panixida/profile-service:latest
    restart: unless-stopped
    environment:
      DB_HOST: profile_db
      DB_PORT: 5432
      POSTGRES_DB: ProfileServiceDb
      DB_USER: postgres
      DB_PASSWORD: 123456789
      ASPNETCORE_ENVIRONMENT: production
      RabbitMQ: rabbitmq
    depends_on:
      - profile_db
      - profile_db_migrator
    networks:
      - app-network
      
  profile_db:
    image: postgres:15
    container_name: profile_db
    restart: always   
    ports:
      - "5434:5432"
    volumes:
      - profile-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ProfileServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    networks:
      - app-network

  profile_db_migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: profile_db_migrator
    restart: on-failure
    environment:
      DB_HOST: profile_db
      DB_PORT: 5432
      POSTGRES_DB: ProfileServiceDb
      DB_USER: postgres
      DB_PASSWORD: 123456789
      ASPNETCORE_ENVIRONMENT: production
      RabbitMQ: rabbitmq
    working_dir: /app
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        dotnet tool install --global dotnet-ef &&
        export PATH="/usr/local/bin:/usr/bin:/bin:/root/.dotnet/tools" &&
        dotnet ef database update --project Services/ProfileService/ProfileService.csproj \
                                  --startup-project Services/ProfileService/ProfileService.csproj
    depends_on:
      - profile_db     
    networks:
      - app-network
     
# Images
  images-service:
    container_name: images-service
    image: ghcr.io/panixida/images-service:latest
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: production
    networks:
      - app-network
      
# Email
  email-service:
    container_name: email-service
    image: ghcr.io/panixida/email-service:latest
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_HOST: email_db
      DB_PORT: 5432
      POSTGRES_DB: EmailServiceDb
      DB_USER: postgres
      DB_PASSWORD: 123456789
      RabbitMQ: rabbitmq
    depends_on:
      - email_db
      - email_db_migrator
    networks:
      - app-network
      
  email_db:
    image: postgres:15
    container_name: email_db
    restart: always   
    ports:
      - "5435:5432"
    volumes:
      - email-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: EmailServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    networks:
      - app-network

  email_db_migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: email_db_migrator
    restart: on-failure
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DB_HOST: email_db
      DB_PORT: 5432
      POSTGRES_DB: EmailServiceDb
      DB_USER: postgres
      DB_PASSWORD: 123456789
    working_dir: /app
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        dotnet tool install --global dotnet-ef &&
        export PATH="/usr/local/bin:/usr/bin:/bin:/root/.dotnet/tools" &&
        dotnet ef database update --project Services/EmailService/EmailService.csproj \
                                  --startup-project Services/EmailService/EmailService.csproj
    depends_on:
      - email_db     
    networks:
      - app-network

# Chats     
  chats-service:
    container_name: chats-service
    image: ghcr.io/panixida/chats-service:latest
    restart: unless-stopped
    environment:
      DB_HOST: chats_db
      DB_PORT: 5432
      POSTGRES_DB: ChatsServiceDb
      DB_USER: postgres
      DB_PASSWORD: 123456789
      ASPNETCORE_ENVIRONMENT: production
    depends_on:
      - chats_db
      - chats_db_migrator
    networks:
      - app-network
      
  chats_db:
    image: postgres:15
    container_name: chats_db
    restart: always   
    ports:
      - "5436:5432"
    volumes:
      - chats-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ChatsServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    networks:
      - app-network

  chats_db_migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: chats_db_migrator
    restart: on-failure
    environment:
      DB_HOST: chats_db
      DB_PORT: 5432
      POSTGRES_DB: ChatsServiceDb
      DB_USER: postgres
      DB_PASSWORD: 123456789
      ASPNETCORE_ENVIRONMENT: production
    working_dir: /app
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        dotnet tool install --global dotnet-ef &&
        export PATH="/usr/local/bin:/usr/bin:/bin:/root/.dotnet/tools" &&
        dotnet ef database update --project Services/ChatsService/ChatsService.csproj \
                                  --startup-project Services/ChatsService/ChatsService.csproj
    depends_on:
      - chats_db     
    networks:
      - app-network
      
# Games     
  games-service:
    container_name: games-service
    image: ghcr.io/panixida/games-service:latest
    restart: unless-stopped
    environment:
      DB_HOST: games_db
      DB_PORT: 5432
      POSTGRES_DB: GamesServiceDb
      DB_USER: postgres
      DB_PASSWORD: 123456789
      ASPNETCORE_ENVIRONMENT: production
    depends_on:
      - games_db
      - games_db_migrator
    networks:
      - app-network
      
  games_db:
    image: postgres:15
    container_name: games_db
    restart: always   
    ports:
      - "5437:5432"
    volumes:
      - games-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: GamesServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    networks:
      - app-network

  games_db_migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: games_db_migrator
    restart: on-failure
    environment:
      DB_HOST: games_db
      DB_PORT: 5432
      POSTGRES_DB: GamesServiceDb
      DB_USER: postgres
      DB_PASSWORD: 123456789
      ASPNETCORE_ENVIRONMENT: production
    working_dir: /app
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        dotnet tool install --global dotnet-ef &&
        export PATH="/usr/local/bin:/usr/bin:/bin:/root/.dotnet/tools" &&
        dotnet ef database update --project Services/GamesService/GamesService.csproj \
                                  --startup-project Services/GamesService/GamesService.csproj
    depends_on:
      - games_db     
    networks:
      - app-network

# Игровые данные 
  game-data-service:
    container_name: game-data-service
    image: ghcr.io/panixida/game-data-service:latest
    restart: unless-stopped
    environment:
      DB_HOST: game_data_db
      DB_PORT: 5432
      POSTGRES_DB: GameDataServiceDb
      DB_USER: postgres
      DB_PASSWORD: 123456789
      ASPNETCORE_ENVIRONMENT: production
    depends_on:
      - game_data_db
      - game_data_db_migrator
    networks:
      - app-network
      
  game_data_db:
    image: postgres:15
    container_name: game_data_db
    restart: always   
    ports:
      - "5438:5432"
    volumes:
      - game-data-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: GameDataServiceDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
    networks:
      - app-network

  game_data_db_migrator:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    container_name: game_data_db_migrator
    restart: on-failure
    environment:
      DB_HOST: game_data_db
      DB_PORT: 5432
      POSTGRES_DB: GameDataServiceDb
      DB_USER: postgres
      DB_PASSWORD: 123456789
      ASPNETCORE_ENVIRONMENT: production
    working_dir: /app
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        dotnet tool install --global dotnet-ef &&
        export PATH="/usr/local/bin:/usr/bin:/bin:/root/.dotnet/tools" &&
        dotnet ef database update --project Services/GameDataService/GameDataService.csproj \
                                  --startup-project Services/GameDataService/GameDataService.csproj
    depends_on:
      - game_data_db     
    networks:
      - app-network

# Билды игроков
  player-builds-service:
    container_name: player-builds-service
    image: ghcr.io/panixida/player-builds-service:latest
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: production
    networks:
      - app-network

# UI      
  frontend-service:
    container_name: frontend-service
    image: ghcr.io/panixida/frontend-service:latest
    restart: unless-stopped
    ports:
      - "9080:9080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      RabbitMQ: rabbitmq
    networks:
      - app-network

# Инфраструктура
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=mixaila17may2003@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=Test1234
    ports:
      - "5050:80"
    networks:
      - app-network
   
  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network
      
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
    command:
      - redis-server
      - --appendonly
      - "yes"
      - --replicaof
      - "no one"
    volumes:
      - redis_data:/data
          
networks:
  app-network:
    driver: bridge
 
volumes:
  profile-database-data:
  email-database-data:
  chats-database-data:
  games-database-data:
  game-data-database-data:
  redis_data:
