name: Build and Push Docker Images

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: PANiXiDA
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push API Gateway image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: APIGateway/Dockerfile
          push: true
          tags: ghcr.io/PANiXiDA/api-gateway:latest

      - name: Build and push GamePlay Service image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Services/GamePlayService/Dockerfile
          push: true
          tags: ghcr.io/PANiXiDA/game-play-service:latest

      - name: Build and push Profile Service image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Services/ProfileService/Dockerfile
          push: true
          tags: ghcr.io/PANiXiDA/profile-service:latest

      - name: Build and push Images Service image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Services/ImagesService/Dockerfile
          push: true
          tags: ghcr.io/PANiXiDA/images-service:latest

      - name: Build and push Email Service image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Services/EmailService/Dockerfile
          push: true
          tags: ghcr.io/PANiXiDA/email-service:latest

      - name: Build and push Chats Service image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Services/ChatsService/Dockerfile
          push: true
          tags: ghcr.io/PANiXiDA/chats-service:latest

      - name: Build and push Games Service image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Services/GamesService/Dockerfile
          push: true
          tags: ghcr.io/PANiXiDA/games-service:latest

      - name: Build and push Game Data Service image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Services/GameDataService/Dockerfile
          push: true
          tags: ghcr.io/PANiXiDA/game-data-service:latest

      - name: Build and push Player Builds Service image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Services/PlayerBuildsService/Dockerfile
          push: true
          tags: ghcr.io/PANiXiDA/player-builds-service:latest

      - name: Build and push Frontend Service image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: FrontendService/Dockerfile
          push: true
          tags: ghcr.io/PANiXiDA/frontend-service:latest
