name: Deploy

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd OldStrategiesForge
            git pull https://${{ secrets.TOKEN }}@github.com/PANiXiDA/OldStrategiesForge.git develop

            # Очистка логов сервера Linux
            echo "Cleaning up logs..."
            sudo journalctl --vacuum-size=100M
            sudo find /var/log -name "*.gz" -type f -delete
            sudo find /var/log -type f -exec truncate -s 0 {} \;

            # Очистка кэша APT
            echo "Cleaning up APT cache..."
            sudo apt clean

            # Остановка контейнеров без удаления данных из базы
            echo "Stopping containers..."
            docker-compose down --remove-orphans

            # Очистка неиспользуемых Docker-ресурсов (контейнеров, образов, сетей и томов)
            echo "Cleaning up Docker resources..."
            docker system prune -f --volumes
            docker image prune -a -f
            docker builder prune -f
            docker volume prune -f
            docker network prune -f

            # Перезапуск контейнеров с пересборкой
            echo "Rebuilding and starting containers..."
            docker-compose up --build -d
